Animals = {
    SmallGame = {
        {model = "a_c_bat_01",                          item = ''},
        {model = "a_c_bluejay_01",                      item = ''},
        {model = "a_c_cardinal_01",                     item = ''},
        {model = "a_c_carolinaparakeet_01",             item = ''},
        {model = "a_c_cedarwaxwing_01",                 item = ''},
        {model = "a_c_chipmunk_01",                     item = ''},
        {model = "a_c_crab_01",                         item = ''},
        {model = "a_c_crawfish_01",                     item = ''},
        {model = "a_c_fishbluegil_01_ms",               item = ''},
        {model = "a_c_fishbluegil_01_sm",               item = ''},
        {model = "a_c_fishbullheadcat_01_ms",           item = ''},
        {model = "a_c_fishbullheadcat_01_sm",           item = ''},
        {model = "a_c_fishchainpickerel_01_ms",         item = ''},
        {model = "a_c_fishchainpickerel_01_sm",         item = ''},
        {model = "a_c_fishchannelcatfish_01_lg",        item = ''},
        {model = "a_c_fishchannelcatfish_01_xl",        item = ''},
        {model = "a_c_fishlakesturgeon_01_lg",          item = ''},
        {model = "a_c_fishlargemouthbass_01_lg",        item = ''},
        {model = "a_c_fishlargemouthbass_01_ms",        item = ''},
        {model = "a_c_fishlongnosegar_01_lg",           item = ''},
        {model = "a_c_fishmuskie_01_lg",                item = ''},
        {model = "a_c_fishnorthernpike_01_lg",          item = ''},
        {model = "a_c_fishperch_01_ms",                 item = ''},
        {model = "a_c_fishperch_01_sm",                 item = ''},
        {model = "a_c_fishrainbowtrout_01_lg",          item = ''},
        {model = "a_c_fishrainbowtrout_01_ms",          item = ''},
        {model = "a_c_fishredfinpickerel_01_ms",        item = ''},
        {model = "a_c_fishredfinpickerel_01_sm",        item = ''},
        {model = "a_c_fishrockbass_01_ms",              item = ''},
        {model = "a_c_fishrockbass_01_sm",              item = ''},
        {model = "a_c_fishsalmonsockeye_01_lg",         item = ''},
        {model = "a_c_fishsalmonsockeye_01_ml",         item = ''},
        {model = "a_c_fishsalmonsockeye_01_ms",         item = ''},
        {model = "a_c_fishsmallmouthbass_01_lg",        item = ''},
        {model = "a_c_fishsmallmouthbass_01_ms",        item = ''},
    	{model = "a_c_frogbull_01",                     item = ''},
        {model = "a_c_muskrat_01",                      item = ''},
        {model = "a_c_oriole_01",                       item = ''},
        {model = "a_c_owl_01",                          item = ''},
    	{model = "a_c_pigeon",                          item = ''},
        {model = "a_c_quail_01",                        item = ''},
        {model = "a_c_rat_01",                          item = ''},
        {model = "a_c_robin_01",                        item = ''},
        {model = "a_c_songbird_01",                     item = ''},
        {model = "a_c_sparrow_01",                      item = ''},
        {model = "a_c_squirrel_01",                     item = ''},
        {model = "a_c_toad_01",                         item = ''},
    	{model = "a_c_woodpecker_01",                   item = ''},
        {model = "a_c_woodpecker_02",                   item = ''},
    },
    BigGame = {
        {model = "a_c_alligator_01",                    price = 1, meat = '', meatqty = 3, pelt = '', peltqty = 1},
        {model = "a_c_alligator_02",                    price = 1, meat = '', meatqty = 3, pelt = '', peltqty = 1},
        {model = "a_c_alligator_03",                    price = 1, meat = '', meatqty = 3, pelt = '', peltqty = 1},
        {model = "a_c_armadillo_01",                    price = 1, meat = '', meatqty = 3, pelt = '', peltqty = 1},
        {model = "a_c_badger_01",                       price = 1, meat = '', meatqty = 3, pelt = '', peltqty = 1},
        {model = "a_c_bearblack_01",                    price = 1, meat = '', meatqty = 3, pelt = '', peltqty = 1},
        {model = "a_c_bear_01",                         price = 1, meat = '', meatqty = 3, pelt = '', peltqty = 1},
        {model = "a_c_beaver_01",                       price = 1, meat = '', meatqty = 3, pelt = '', peltqty = 1},
        {model = "a_c_bighornram_01",                   price = 1, meat = '', meatqty = 3, pelt = '', peltqty = 1},
        {model = "a_c_boarlegendary_01",                price = 1, meat = '', meatqty = 3, pelt = '', peltqty = 1},
        {model = "a_c_boar_01",                         price = 1, meat = '', meatqty = 3, pelt = '', peltqty = 1},
        {model = "a_c_buck_01",                         price = 1, meat = '', meatqty = 3, pelt = '', peltqty = 1},
        {model = "a_c_buffalo_01",                      price = 1, meat = '', meatqty = 3, pelt = '', peltqty = 1},
        {model = "a_c_buffalo_tatanka_01",              price = 1, meat = '', meatqty = 3, pelt = '', peltqty = 1},
        {model = "a_c_bull_01",                         price = 1, meat = '', meatqty = 3, pelt = '', peltqty = 1},
        {model = "a_c_californiacondor_01",             price = 1, meat = '', meatqty = 3, pelt = '', peltqty = 1},
    	{model = "a_c_cat_01",                          price = 1, meat = '', meatqty = 3, pelt = '', peltqty = 1},
        {model = "a_c_chicken_01",                      price = 1, meat = '', meatqty = 3, pelt = '', peltqty = 1},
        {model = "a_c_cormorant_01",                    price = 1, meat = '', meatqty = 3, pelt = '', peltqty = 1},
        {model = "a_c_cougar_01",                       price = 1, meat = '', meatqty = 3, pelt = '', peltqty = 1},
        {model = "a_c_cow",                             price = 1, meat = '', meatqty = 3, pelt = '', peltqty = 1},
        {model = "a_c_coyote_01",                       price = 3, meat = 'provision_meat_stringy', meatqty = 3, pelt = 'provision_coyote_fur', peltqty = 1},
    	{model = "a_c_cranewhooping_01",                price = 1, meat = '', meatqty = 1, pelt = '', peltqty = 1},
        {model = "a_c_crow_01",                         price = 1, meat = '', meatqty = 1, pelt = '', peltqty = 1},
        {model = "a_c_deer_01",                         price = 1, meat = '', meatqty = 1, pelt = '', peltqty = 1},
    	{model = "a_c_donkey_01",                       price = 1, meat = '', meatqty = 1, pelt = '', peltqty = 1},
        {model = "a_c_duck_01",                         price = 1, meat = '', meatqty = 1, pelt = '', peltqty = 1},
        {model = "a_c_eagle_01",                        price = 1, meat = '', meatqty = 1, pelt = '', peltqty = 1},
        {model = "a_c_egret_01",                        price = 1, meat = '', meatqty = 1, pelt = '', peltqty = 1},
        {model = "a_c_elk_01",                          price = 1, meat = '', meatqty = 1, pelt = '', peltqty = 1},
    	{model = "a_c_fox_01",                          price = 1, meat = '', meatqty = 1, pelt = '', peltqty = 1},
        {model = "a_c_gilamonster_01",                  price = 1, meat = '', meatqty = 1, pelt = '', peltqty = 1},
        {model = "a_c_goat_01",                         price = 1, meat = '', meatqty = 1, pelt = '', peltqty = 1},
        {model = "a_c_goosecanada_01",                  price = 1, meat = '', meatqty = 1, pelt = '', peltqty = 1},
        {model = "a_c_hawk_01",                         price = 1, meat = '', meatqty = 1, pelt = '', peltqty = 1},
        {model = "a_c_heron_01",                        price = 1, meat = '', meatqty = 1, pelt = '', peltqty = 1},
        {model = "a_c_iguanadesert_01",                 price = 1, meat = '', meatqty = 1, pelt = '', peltqty = 1},
        {model = "a_c_iguana_01",                       price = 1, meat = '', meatqty = 1, pelt = '', peltqty = 1},
        {model = "a_c_javelina_01",                     price = 1, meat = '', meatqty = 1, pelt = '', peltqty = 1},
        {model = "a_c_lionmangy_01",                    price = 1, meat = '', meatqty = 1, pelt = '', peltqty = 1},
        {model = "a_c_loon_01",                         price = 1, meat = '', meatqty = 1, pelt = '', peltqty = 1},
        {model = "a_c_moose_01",                        price = 1, meat = '', meatqty = 1, pelt = '', peltqty = 1},
    	{model = "a_c_ox_01",                           price = 1, meat = '', meatqty = 1, pelt = '', peltqty = 1},
        {model = "a_c_panther_01",                      price = 1, meat = '', meatqty = 1, pelt = '', peltqty = 1},
        {model = "a_c_parrot_01",                       price = 1, meat = '', meatqty = 1, pelt = '', peltqty = 1},
        {model = "a_c_pelican_01",                      price = 1, meat = '', meatqty = 1, pelt = '', peltqty = 1},
        {model = "a_c_pheasant_01",                     price = 1, meat = 'provision_meat_gamey_bird', meatqty = 3, pelt = 'generic_animal_feather_large', peltqty = 3},
        {model = "a_c_pig_01",                          price = 1, meat = '', meatqty = 3, pelt = '', peltqty = 1},
        {model = "a_c_possum_01",                       price = 1, meat = '', meatqty = 3, pelt = '', peltqty = 1},
        {model = "a_c_prairiechicken_01",               price = 1, meat = '', meatqty = 3, pelt = '', peltqty = 1},
        {model = "a_c_pronghorn_01",                    price = 1, meat = '', meatqty = 3, pelt = '', peltqty = 1},
    	{model = "a_c_rabbit_01",                       price = 1, meat = '', meatqty = 3, pelt = '', peltqty = 1},
        {model = "a_c_raccoon_01",                      price = 1, meat = '', meatqty = 3, pelt = '', peltqty = 1},
        {model = "a_c_raven_01",                        price = 1, meat = '', meatqty = 3, pelt = '', peltqty = 1},
        {model = "a_c_redfootedbooby_01",               price = 1, meat = '', meatqty = 3, pelt = '', peltqty = 1},
    	{model = "a_c_rooster_01",                      price = 1, meat = '', meatqty = 3, pelt = '', peltqty = 1},
        {model = "a_c_roseatespoonbill_01",             price = 1, meat = '', meatqty = 3, pelt = '', peltqty = 1},
        {model = "a_c_seagull_01",                      price = 1, meat = '', meatqty = 3, pelt = '', peltqty = 1},
        {model = "a_c_sharkhammerhead_01",              price = 1, meat = '', meatqty = 3, pelt = '', peltqty = 1},
        {model = "a_c_sharktiger",                      price = 1, meat = '', meatqty = 3, pelt = '', peltqty = 1},
        {model = "a_c_sheep_01",                        price = 1, meat = '', meatqty = 3, pelt = '', peltqty = 1},
        {model = "a_c_skunk_01",                        price = 1, meat = '', meatqty = 3, pelt = '', peltqty = 1},
        {model = "a_c_snakeblacktailrattle_01",         price = 1, meat = '', meatqty = 3, pelt = '', peltqty = 1},
        {model = "a_c_snakeblacktailrattle_pelt_01",    price = 1, meat = '', meatqty = 3, pelt = '', peltqty = 1},
        {model = "a_c_snakeferdelance_01",              price = 1, meat = '', meatqty = 3, pelt = '', peltqty = 1},
        {model = "a_c_snakeferdelance_pelt_01",         price = 1, meat = '', meatqty = 3, pelt = '', peltqty = 1},
        {model = "a_c_snakeredboa10ft_01",              price = 1, meat = '', meatqty = 3, pelt = '', peltqty = 1},
        {model = "a_c_snakeredboa_01",                  price = 1, meat = '', meatqty = 3, pelt = '', peltqty = 1},
        {model = "a_c_snakeredboa_pelt_01",             price = 1, meat = '', meatqty = 3, pelt = '', peltqty = 1},
        {model = "a_c_snakewater_01",                   price = 1, meat = '', meatqty = 3, pelt = '', peltqty = 1},
        {model = "a_c_snakewater_pelt_01",              price = 1, meat = '', meatqty = 3, pelt = '', peltqty = 1},
        {model = "a_c_snake_01",                        price = 1, meat = '', meatqty = 3, pelt = '', peltqty = 1},
        {model = "a_c_turkeywild_01",                   price = 1, meat = '', meatqty = 3, pelt = '', peltqty = 1},
        {model = "a_c_turkey_01",                       price = 1, meat = '', meatqty = 3, pelt = '', peltqty = 1},
        {model = "a_c_turkey_02",                       price = 1, meat = '', meatqty = 3, pelt = '', peltqty = 1},
        {model = "a_c_turtlesea_01",                    price = 1, meat = '', meatqty = 3, pelt = '', peltqty = 1},
        {model = "a_c_turtlesnapping_01",               price = 1, meat = '', meatqty = 3, pelt = '', peltqty = 1},
        {model = "a_c_vulture_01",                      price = 1, meat = '', meatqty = 3, pelt = '', peltqty = 1},
        {model = "A_C_Wolf",                            price = 1, meat = '', meatqty = 3, pelt = '', peltqty = 1},
        {model = "a_c_wolf_medium",                     price = 1, meat = '', meatqty = 3, pelt = '', peltqty = 1},
        {model = "a_c_wolf_small",                      price = 1, meat = '', meatqty = 3, pelt = '', peltqty = 1},
    }
}